const path = {
  PUBLIC: '/*',
  HOME: '',
  LOGIN: 'login',
  MY_MUSIC: 'mymusic',
  ALBUM__TITLE__PID: 'album/:title/:pid',
  PLAYLIST__TITLE__PID: 'playlist/:title/:pid',
  HUB: 'hub',
  MUSIC_VIDEO: 'the-loai-video',
  NEW_MUSIC: 'moi-phat-hanh',
  TOP_100: 'top100',
  SEARCH: 'tim-kiem',
  SEARCH_ALL: 'tat-ca',
  SEARCH_SONGS: 'bai-hat',
  SEARCH_PLAYLISTS: 'playlist',
  SEARCH_ARTIST: 'artist',
  ARTIST: ':artist',
  ARTIST_2ND: 'nghe-si/:artist',
  ZING_CHART: 'zing-chart',
}
export default path