const actionTypes = {
  GET_HOME: 'GET_HOME',
  GET_HOME_DATA: 'GET_HOME_DATA',
  SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',
  SET_CURRENT_PLAYLIST_ID: 'SET_CURRENT_SET_CURRENT_PLAYLIST_ID_ID',
  // Music
  TOGGLE_PLAY_MUSIC: 'PLAY'
}

export default actionTypes