const actionTypes = {
  GET_HOME_DATA: 'GET_HOME_DATA',
  TOGGLE_SHOW_PLAYLIST: 'TOGGLE_SHOW_PLAYLIST',
  // Music
  TOGGLE_PLAY_MUSIC: 'PLAY',
  SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',
  SET_CURRENT_PLAYLIST_ID: 'SET_CURRENT_SET_ID',
  SET_CURRENT_PLAYLIST: 'SET_CURRENT_PLAYLIST',
  SET_REPEAT_VALUE: 'SET_REPEAT_VALUE',
  TOGGLE_SHUFFLE: 'TOGGLE_SHUFFLE',
  SET_PLAYLIST_BEFORE_SHUFFLE: 'SET_PLAYLIST_BEFORE_SHUFFLE',
  CLEAR_CURRENT_PLAYLIST: 'CLEAR_CURRENT_PLAYLIST',
  CLEAR_PLAYLIST_BEFORE_SHUFFLE: 'CLEAR_PLAYLIST_BEFORE_SHUFFLE',
  SET_HISTORY: 'SET_HISTORY',
  PUSH_SONG_FROM_HISTORY_TO_CURRENT_PLAYLIST: 'PUSH_SONG_FROM_HISTORY_TO_CURRENT_PLAYLIST',
}

export default actionTypes